from setuptools import setup, find_packages

setup(
    name="autonomous_tuning",
    version="0.1.0",
    author="Jonas Schuff",
    author_email="jonas.schuff@materials.ox.ac.uk",
    description="Fully autonomous tuning of spin qubits with charge transport measurements using machine learning",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/oxquantum-repo/fully-autonomous-tuning",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
    install_requires=[
        'numpy',
        'matplotlib',
        'opencv-python',
        'scikit-image',
        'scipy',
        'qcodes',
        'jupyterlab',
        'jupyter',
        'toml',
        'tqdm',
        'torchvision',
        'chardet',
        'seaborn',
        'scikit-learn',
        'opencv-contrib-python',
        'zhinst',
        'zhinst-qcodes',
        'nidaqmx',
        'treelib',
        'tenacity',
        'fastai'
    ],
)
